---
- hosts: localhost
  connection: local

  vars: 
    my_var_one: "some string for var one"
    my_var_two: "some string for var two"

  tasks: 
  - name: set stats on some variables
    set_stats: 
      data: 
        var_one: "{{ my_var_one }}"
        var_two: "{{ my_var_two }}"
